import{i as u}from"./assets/vendor-I1I71QQ2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const o of n.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();function m(e){const r=Array.isArray(e)?e:[e];return d(r)}function c(e){return`<li class='list-items'>
          <h1 class="item-title">${e.title}</h1>
          <div class="buttons">
           <a href="${e.url}" target="_blank" class="url-item">Visit</a>
          <button type="button" class="delete-btn">delete</button>
      <button type="button" class="edit-btn">edit</button>
      </div>
        </li>`}function d(e){return e.map(c).join("")}function f(e){const r=JSON.parse(localStorage.getItem("bookmarks"))||[];r.push(e),localStorage.setItem("bookmarks",JSON.stringify(r))}function p(e){if(!e.target.classList.contains("delete-btn"))return;const r=e.target.closest(".list-items"),s=r.firstElementChild.textContent;r.remove();const i=JSON.parse(localStorage.getItem("bookmarks"))||[],t=i.findIndex(n=>n.title===s);t!==-1&&i.splice(t,1),localStorage.setItem("bookmarks",JSON.stringify(i))}function b(e){if(!e.target.classList.contains("edit-btn"))return;const r=e.target.closest(".list-items"),s=e.target;if(s.textContent==="edit"){const i=r.querySelector("h1"),t=r.querySelector("a"),n=document.createElement("input");n.type="text";const o=document.createElement("input");o.type="url",n.value=i.textContent,o.value=t.href,i.replaceWith(n),t.replaceWith(o),s.textContent="save",n.focus()}else if(s.textContent==="save"){const i=r.querySelector('input[type="text"]'),t=r.querySelector('input[type="url"]'),n=document.createElement("h1");n.textContent=i.value;const o=document.createElement("a");o.href=t.value,o.textContent=t.value,o.href=t.value,o.textContent="Visit",o.target="_blank",o.classList.add("url-item"),i.replaceWith(n),t.replaceWith(o),s.textContent="Edit"}}const k={form:document.querySelector(".form"),bookMarkList:document.querySelector(".bookmark-list")},{form:l,bookMarkList:a}=k;document.addEventListener("DOMContentLoaded",()=>{const e=JSON.parse(localStorage.getItem("bookmarks"));if(!e)return;const r=m(e);a.innerHTML=r});l.addEventListener("submit",g);function g(e){e.preventDefault();const r=new FormData(l),s={title:r.get("title").trim(),url:r.get("url").trim()};if(!s.title||!s){u.show({message:"Please fill all fields!"});return}f(s);const i=c(s);a.insertAdjacentHTML("beforeend",i),l.reset()}a.addEventListener("click",p);a.addEventListener("click",b);
//# sourceMappingURL=index.js.map
