import{i as u}from"./assets/vendor-I1I71QQ2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();function m(e){const r=Array.isArray(e)?e:[e];return d(r)}function c(e){return`<li class='list-items'>
  <div class="text-item">
          <h1 class="item-title white-wrapper">${e.title}</h1>
          <a href="${e.url}" target="blank class="url-item ">Visit</a>
          </div>
          <div class="buttons">
          <button type="button" class="delete-btn">delete</button>
      <button type="button" class="edit-btn">edit</button>
      </div>
        </li>`}function d(e){return e.map(c).join("")}function f(e){const r=JSON.parse(localStorage.getItem("bookmarks"))||[];r.push(e),localStorage.setItem("bookmarks",JSON.stringify(r))}function p(e){if(!e.target.classList.contains("delete-btn"))return;const r=e.target.closest(".list-items"),o=r.firstElementChild.textContent;r.remove();const s=JSON.parse(localStorage.getItem("bookmarks"))||[],t=s.findIndex(n=>n.title===o);t!==-1&&s.splice(t,1),localStorage.setItem("bookmarks",JSON.stringify(s))}function b(e){if(!e.target.classList.contains("edit-btn"))return;const r=e.target.closest(".list-items"),o=e.target;if(o.textContent==="edit"){const s=r.querySelector("h1"),t=r.querySelector("a"),n=document.createElement("input");n.type="text";const i=document.createElement("input");i.type="url",n.value=s.textContent,i.value=t.textContent,s.replaceWith(n),t.replaceWith(i),o.textContent="save",n.focus()}else if(o.textContent==="save"){const s=r.querySelector('input[type="text"]'),t=r.querySelector('input[type="url"]'),n=document.createElement("h1");n.textContent=s.value;const i=document.createElement("a");i.href=t.value,i.textContent=t.value,i.target="_blank",s.replaceWith(n),t.replaceWith(i),o.textContent="Edit"}}const k={form:document.querySelector(".form"),bookMarkList:document.querySelector(".bookmark-list")},{form:l,bookMarkList:a}=k;document.addEventListener("DOMContentLoaded",()=>{const e=JSON.parse(localStorage.getItem("bookmarks"));if(!e)return;const r=m(e);a.innerHTML=r});l.addEventListener("submit",g);function g(e){e.preventDefault();const r=new FormData(l),o={title:r.get("title").trim(),url:r.get("url").trim()};if(!o.title||!o){u.show({message:"Please fill all fields!"});return}f(o);const s=c(o);a.insertAdjacentHTML("beforeend",s),l.reset()}a.addEventListener("click",p);a.addEventListener("click",b);
//# sourceMappingURL=index.js.map
