import{i as u}from"./assets/vendor-I1I71QQ2.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();function m(e){const n=Array.isArray(e)?e:[e];return d(n)}function c(e){return`<li class='list-items'>
  <div class="text-item">
          <h1 class="item-title">${e.title}</h1>
          <a href="${e.url}" target="blank class="url-item">Visit</a>
          </div>
          <div class="buttons">
          <button type="button" class="delete-btn">delete</button>
      <button type="button" class="edit-btn">edit</button>
      </div>
        </li>`}function d(e){return e.map(c).join("")}function f(e){const n=JSON.parse(localStorage.getItem("bookmarks"))||[];n.push(e),localStorage.setItem("bookmarks",JSON.stringify(n))}function p(e){if(!e.target.classList.contains("delete-btn"))return;const n=e.target.closest(".list-items"),o=n.firstElementChild.textContent;n.remove();const s=JSON.parse(localStorage.getItem("bookmarks"))||[],t=s.findIndex(r=>r.title===o);t!==-1&&s.splice(t,1),localStorage.setItem("bookmarks",JSON.stringify(s))}function b(e){if(!e.target.classList.contains("edit-btn"))return;const n=e.target.closest(".list-items"),o=e.target;if(o.textContent==="edit"){const s=n.querySelector("h1"),t=n.querySelector("a"),r=document.createElement("input");r.type="text";const i=document.createElement("input");i.type="url",r.value=s.textContent,i.value=t.textContent,s.replaceWith(r),t.replaceWith(i),o.textContent="save",r.focus()}else if(o.textContent==="save"){const s=n.querySelector('input[type="text"]'),t=n.querySelector('input[type="url"]'),r=document.createElement("h1");r.textContent=s.value;const i=document.createElement("a");i.href=t.value,i.textContent=t.value,i.target="_blank",s.replaceWith(r),t.replaceWith(i),o.textContent="Edit"}}const k={form:document.querySelector(".form"),bookMarkList:document.querySelector(".bookmark-list")},{form:l,bookMarkList:a}=k;document.addEventListener("DOMContentLoaded",()=>{const e=JSON.parse(localStorage.getItem("bookmarks"));if(!e)return;const n=m(e);a.innerHTML=n});l.addEventListener("submit",g);function g(e){e.preventDefault();const n=new FormData(l),o={title:n.get("title").trim(),url:n.get("url").trim()};if(!o.title||!o){u.show({message:"Please fill all fields!"});return}f(o);const s=c(o);a.insertAdjacentHTML("beforeend",s),l.reset()}a.addEventListener("click",p);a.addEventListener("click",b);
//# sourceMappingURL=index.js.map
